const uWaterloo = {
  "uw.mc": new Set(["uw.m3:2", "uw.dc:1", "uw.c2:3", "uw.qnc:5", "uw.slc:4"]),
  "uw.m3": new Set(["uw.mc:2"]),
  "uw.dc": new Set(["uw.mc:1", "uw.c2:2"]),
  "uw.c2": new Set(["uw.dc:2", "uw.mc:3", "uw.c1:4"]),
  "uw.qnc": new Set(["uw.mc:5", "uw.b2:3", "uw.stc:4"]),
  "uw.slc": new Set(["uw.pac:6", "uw.mc:4"]),
  "uw.c1": new Set(["uw.c2:4", "uw.b1:2", "uw.eit:3"]),
  "uw.eit": new Set(["uw.phy:2", "uw.c1:3"]),
  "uw.phy": new Set(["uw.eit:2", "uw.e2:4"]),
  "uw.e2": new Set(["uw.phy:4", "uw.e1:3"]),
  "uw.e1": new Set(["uw.e2:3", "uw.rch:1"]),
  "uw.rch": new Set(["uw.cph:5", "uw.e1:1"]),
  "uw.cph": new Set(["uw.rch:5"]),
  "uw.b2": new Set(["uw.b1:2", "uw.qnc:3"]),
  "uw.b1": new Set(["uw.c1:2", "uw.b2:2"]),
  "uw.pac": new Set(["uw.slc:6"]),
  "uw.e3": new Set(["uw.e5:1"]),
  "uw.e5": new Set(["uw.e3:1", "uw.ech:2", "uw.e7:4"]),
  "uw.ech": new Set(["uw.e5:2"]),
  "uw.e7": new Set(["uw.e5:4", "uw.e6:3"]),
  "uw.e6": new Set(["uw.e7:3"]),
  "uw.stc": new Set(["uw.nh:2"]),
  "uw.nh": new Set(["uw.stc:2", "uw.al:1"]),
  "uw.al": new Set(["uw.ml:3", "uw.nh:1"]),
  "uw.ml": new Set(["uw.ev1:2", "uw.al:3"]),
  "uw.ev1": new Set(["uw.ev2:1", "uw.ml:2"]),
  "uw.ev2": new Set(["uw.ev1:1", "uw.ev3:3"]),
  "uw.ev3": new Set(["uw.ev2:3"]),
  "uw.dp": new Set(),
  "uw.gh": new Set(),
  "uw.hh": new Set(["uw.tc:1"]),
  "uw.tc": new Set(["uw.sch:2", "uw.hh:1"]),
  "uw.sch": new Set(["uw.tc:2"]),
  "uw.pas": new Set(),
};

module.exports = uWaterloo;
